import Head from 'next/head'
import NavBar from '../components/navbar';
import Footer from '../components/footer';

import React, { useContext, useEffect, useRef, useState } from 'react'
import axios from 'axios';
import jwt from 'jsonwebtoken';

function WebLayout({ children }) {
  
  return (
    <> 
      {/* <Head>
        <title>Fe-Sektak</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
     
      <NavBar />
      <main>{children}</main>
      <Footer />
    </>
  )
}

export default WebLayout
